### PR TITLE
Add resource delete method

### PR DESCRIPTION
**Pull request by mattkime**
Should be straight forward.

### CODE REVIEW

**Comment by alicoding** [comment]
Hey @mattkime ! Thank you so much for the PR! Do you think you could provide with any simple test at all? Not super picky about it after reading your code, but just to cover if the API changed again in the near future or something? :)

**Comment by mattkime** [comment]
certainly! sorry, should have seen that.

**Comment by mattkime** [comment]
@alicoding thanks for the merge - could you tag a release and push to npm?

**Comment by alicoding** [comment]
@mattkime done sir :D

**Pull request merged**
