### PR TITLE
Fix travis deployment

### PR DESCRIPTION
**Pull request by mattkime**

### CODE REVIEW

**Comment by mattkime** [comment]
@alicoding this should work once NPM_TOKEN is supplied to the travis build. 

Either you can do this or I can do it if I'm given collaborator privs on npm and have config privs on travis.

**Comment by alicoding** [comment]
@mattkime I just added you to NPM but I don't know how to do that on Travis since I don't see that option anywhere?

**Comment by mattkime** [comment]
hrm, you might need to give me more privs on github

**Comment by alicoding** [comment]
@mattkime you may just need to accept the invite I've sent you? https://github.com/alicoding/node-transifex/invitations

**Comment by mattkime** [comment]
@alicoding nah, already accepted that. might be easier to pair on this, if you've used screenhero. 

we should also set up a github deploy key so travis can tag branches

**Comment by alicoding** [comment]
Let me try to add that ENV once I get back to my computer in 15b mins

**Comment by alicoding** [comment]
Done. I just added NPM_TOKEN to travis setting for this project.

**Comment by alicoding** [comment]
I followed the instruction from this site : https://remysharp.com/2015/10/26/using-travis-with-private-npm-deps

and I added the env here 
screen shot 2017-09-08 at 1 20 11 pm

but it's still failing on that 

```
$ echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

3.60s$ npm install 

Error: Failed to replace env in config: ${NPM_TOKEN}
```

**Comment by mattkime** [comment]
I'll take a look

**Comment by alicoding** [comment]
I'm just going to merge this and fix broken travis later.

**Pull request merged**
